export const columns = [
  { key: "id", label: "ID" },
  { key: "name", label: "Name", isSticky: true },
  { key: "age", label: "Age" },
  { key: "gender", label: "Gender" },
  { key: "email", label: "Email", isSticky: true },
  { key: "phone", label: "Phone" },
  { key: "address", label: "Address" },
  { key: "city", label: "City" },
  { key: "state", label: "State" },
  { key: "zip", label: "Zip" },
];

export const data = [
  {
    id: 1,
    name: "John Doe",
    age: 35,
    gender: "Male",
    email: "johndoe@example.com",
    phone: "(123) 456-7890",
    address: "123 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 28,
    gender: "Female",
    email: "janesmith@example.com",
    phone: "(123) 456-7890",
    address: "456 Second St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 3,
    name: "Bob Johnson",
    age: 42,
    gender: "Male",
    email: "bjohnson@example.com",
    phone: "(123) 456-7890",
    address: "789 Third St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 4,
    name: "Emily Davis",
    age: 31,
    gender: "Female",
    email: "edavis@example.com",
    phone: "(123) 456-7890",
    address: "101 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 5,
    name: "Mark Wilson",
    age: 25,
    gender: "Male",
    email: "mwilson@example.com",
    phone: "(123) 456-7890",
    address: "222 Fourth St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 6,
    name: "Sarah Lee",
    age: 38,
    gender: "Female",
    email: "slee@example.com",
    phone: "(123) 456-7890",
    address: "333 Fifth St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 7,
    name: "David Chen",
    age: 49,
    gender: "Male",
    email: "dchen@example.com",
    phone: "(123) 456-7890",
    address: "444 Sixth St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 8,
    name: "Olivia Brown",
    age: 29,
    gender: "Female",
    email: "obrown@example.com",
    phone: "(123) 456-7890",
    address: "555 Seventh St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 9,
    name: "Mike Thompson",
    age: 36,
    gender: "Male",
    email: "mthompson@example.com",
    phone: "(123) 456-7890",
    address: "666 Ninth St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 10,
    name: "Linda Nguyen",
    age: 27,
    gender: "Female",
    email: "lnguyen@example.com",
    phone: "(123) 456-7890",
    address: "777 Tenth St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
];
